---
server:
  port: 15000

spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: false
        #        show_sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        order_by.default_null_ordering: last

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?reWriteBatchedInserts=true
    username: postgres
    password: postgres

  liquibase:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics, mappings, prometheus
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full